CREATE TABLE public.DOMAIN
(
	ID  SERIAL NOT NULL PRIMARY KEY,
	NAME VARCHAR(24) NOT NULL PRIMARY KEY
);

CREATE TABLE public.COMPONENT
(
	ID  SERIAL NOT NULL PRIMARY KEY,
    DOMAIN_ID INT NOT NULL references public.DOMAIN(ID),
	NAME VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(160) NOT NULL
);

CREATE TABLE public.CHARACTERISTIC
(
	ID  SERIAL NOT NULL PRIMARY KEY,
    DOMAIN_ID INT NOT NULL references public.DOMAIN(ID),
	NAME VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(160) NOT NULL
);

INSERT INTO DOMAIN (NAME) VALUES ('Bacteria');
INSERT INTO DOMAIN (NAME) VALUES ('Archaea');
INSERT INTO DOMAIN (NAME) VALUES ('Eukarya');

INSERT INTO CHARACTERISTIC (DOMAIN_ID, NAME, DESCRIPTION) VALUES (1, 'Cell Type', 'Prokaryotic');
INSERT INTO CHARACTERISTIC (DOMAIN_ID, NAME, DESCRIPTION) VALUES (2, 'Cell Type', 'Prokaryotic');
INSERT INTO CHARACTERISTIC (DOMAIN_ID, NAME, DESCRIPTION) VALUES (3, 'Cell Type', 'Eukaryotic');


INSERT INTO CHARACTERISTIC (DOMAIN_ID, NAME, DESCRIPTION) VALUES (1, 'Antibiotic Sensitivity', 'Yes');
INSERT INTO CHARACTERISTIC (DOMAIN_ID, NAME, DESCRIPTION) VALUES (2, 'Antibiotic Sensitivity', 'No');
INSERT INTO CHARACTERISTIC (DOMAIN_ID, NAME, DESCRIPTION) VALUES (3, 'Antibiotic Sensitivity', 'No');


INSERT INTO COMPONENT (DOMAIN_ID, NAME, DESCRIPTION) VALUES (1, 'Cell Wall', 'Made of peptidoglycan');
INSERT INTO COMPONENT (DOMAIN_ID, NAME, DESCRIPTION) VALUES (2, 'Cell Wall', 'Does not contain peptidoglycan');
INSERT INTO COMPONENT (DOMAIN_ID, NAME, DESCRIPTION) VALUES (3, 'Cell Wall', 'In plants and fungi, composed of polysaccharides');

INSERT INTO COMPONENT (DOMAIN_ID, NAME, DESCRIPTION) VALUES (1, 'First amino acid during protein synthesis', 'Formylmethionine');
INSERT INTO COMPONENT (DOMAIN_ID, NAME, DESCRIPTION) VALUES (2, 'First amino acid during protein synthesis', 'Methionine');
INSERT INTO COMPONENT (DOMAIN_ID, NAME, DESCRIPTION) VALUES (3, 'First amino acid during protein synthesis', 'Methionine');

INSERT INTO COMPONENT (DOMAIN_ID, NAME, DESCRIPTION) VALUES (1, 'DNA', 'Mostly circular chromosome and plasmids');
INSERT INTO COMPONENT (DOMAIN_ID, NAME, DESCRIPTION) VALUES (2, 'DNA', 'Circular chromosome and plasmids');
INSERT INTO COMPONENT (DOMAIN_ID, NAME, DESCRIPTION) VALUES (3, 'DNA', 'Linear chromosome, rarely plasmids');

INSERT INTO COMPONENT (DOMAIN_ID, NAME, DESCRIPTION) VALUES (1, 'Histones', 'No');
INSERT INTO COMPONENT (DOMAIN_ID, NAME, DESCRIPTION) VALUES (2, 'Histones', 'Yes');
INSERT INTO COMPONENT (DOMAIN_ID, NAME, DESCRIPTION) VALUES (3, 'Histones', 'Yes');

INSERT INTO COMPONENT (DOMAIN_ID, NAME, DESCRIPTION) VALUES (1, 'Organelles', 'No');
INSERT INTO COMPONENT (DOMAIN_ID, NAME, DESCRIPTION) VALUES (2, 'Organelles', 'No');
INSERT INTO COMPONENT (DOMAIN_ID, NAME, DESCRIPTION) VALUES (3, 'Organelles', 'Yes');

INSERT INTO COMPONENT (DOMAIN_ID, NAME, DESCRIPTION) VALUES (1, 'Ribosomes', '	70S');
INSERT INTO COMPONENT (DOMAIN_ID, NAME, DESCRIPTION) VALUES (2, 'Ribosomes', '	70S');
INSERT INTO COMPONENT (DOMAIN_ID, NAME, DESCRIPTION) VALUES (3, 'Ribosomes', '80S');

-- For visualization of data.
SELECT * FROM DOMAIN INNER JOIN CHARACTERISTIC ON DOMAIN.ID = CHARACTERISTIC.DOMAIN_ID;

SELECT * FROM DOMAIN INNER JOIN COMPONENT ON DOMAIN.ID = COMPONENT.DOMAIN_ID;

SELECT d.NAME, ch.NAME, ch.DESCRIPTION FROM DOMAIN d INNER JOIN CHARACTERISTIC ch ON d.ID = ch.DOMAIN_ID;

SELECT ch.NAME, ch.DESCRIPTION FROM DOMAIN d INNER JOIN CHARACTERISTIC ch ON d.ID = ch.DOMAIN_ID WHERE d.ID = 1;

SELECT c.NAME AS Compnent, c.DESCRIPTION FROM DOMAIN d INNER JOIN COMPONENT c ON d.ID = c.DOMAIN_ID WHERE d.ID = 1;
SELECT c.NAME AS Compnent, c.DESCRIPTION FROM DOMAIN d INNER JOIN COMPONENT c ON d.ID = c.DOMAIN_ID WHERE d.ID = 2;
SELECT c.NAME AS Compnent, c.DESCRIPTION FROM DOMAIN d INNER JOIN COMPONENT c ON d.ID = c.DOMAIN_ID WHERE d.ID = 3;


-- Initial inserts collected from 
-- J. Stearns, M. Surette, THE DIFFERENCES AMONG BACTERIA, ARCHAEA, AND EUKARYOTIC MICROORGANISMS, Microbiology For Dummies, Online Available: https://www.dummies.com/education/science/biology/the-differences-among-bacteria-archaea-and-eukaryotic-microorganisms/